/* ==== Test Created with Cypress Studio ==== */
it('completeRun', function() {
  /* ==== Generated with Cypress Studio ==== */
  cy.visit('http://localhost:5173/');
  cy.get('#\\:r1\\:').click();
  cy.get('#\\:r3\\:').clear('I');
  cy.get('#\\:r3\\:').type('Ignacio Santos Alonso');
  cy.get('#\\:r5\\:').clear();
  cy.get('#\\:r5\\:').type('email');
  cy.get('#\\:r5\\:').clear('email"');
  cy.get('#\\:r5\\:').type('email@mail.com');
  cy.get('#\\:r7\\:').clear('S');
  cy.get('#\\:r7\\:').type('Sevilla');
  cy.get('body').click();
  cy.get('[data-value="AQ"]').click();
  cy.get('#\\:r9\\:').clear('6');
  cy.get('#\\:r9\\:').type('677123456');
  cy.get('#\\:rb\\:').clear('i');
  cy.get('#\\:rb\\:').type('ignacio.com');
  cy.get('.css-yd8sa2 > :nth-child(5)').click();
  cy.get('#\\:rb\\:').clear();
  cy.get('#\\:rb\\:').type('www.ignacio.com');
  cy.get('[data-testid="ArrowForwardIosIcon"]').click();
  cy.get('.css-j0ozid > .MuiBox-root > .MuiFormControl-root').click();
  cy.get('[data-testid="ArrowBackIosRoundedIcon"]').click();
  cy.get('#\\:r11\\:').click();
  cy.get('#\\:rl\\:').clear('C');
  cy.get('#\\:rl\\:').type('University of education 1');
  cy.get('#\\:rn\\:').clear();
  cy.get('#\\:rn\\:').type('Certification on one');
  cy.get('#\\:rp\\:').click();
  cy.get('.css-j0ozid > .MuiBox-root > .MuiFormControl-root').click();
  cy.get('#\\:r2f\\:').click();
  cy.get('#\\:rl\\:').clear('C');
  cy.get('#\\:rl\\:').type('Center for studies 2');
  cy.get('#\\:rn\\:').clear('C');
  cy.get('#\\:rn\\:').type('Certification 2');
  cy.get('#\\:rp\\:').click();
  cy.get('[data-testid="ArrowForwardIosIcon"]').click();
  cy.get('.css-149sczi > :nth-child(2) > .MuiBox-root > .MuiFormControl-root').click();
  cy.get('[data-testid="ArrowBackIosRoundedIcon"] > path').click();
  cy.get('#\\:r3f\\:').click();
  cy.get(':nth-child(3) > .MuiBox-root > .MuiFormControl-root').click();
  cy.get('#\\:r4l\\:').click();
  cy.get('#\\:r33\\:').clear('F');
  cy.get('#\\:r33\\:').type('First company');
  cy.get('#\\:r35\\:').clear();
  cy.get('#\\:r35\\:').type('First position');
  cy.get(':nth-child(3) > .MuiBox-root > .MuiFormControl-root').click();
  cy.get('[data-testid="ArrowBackIosRoundedIcon"] > path').click();
  cy.get('#\\:r5h\\:').click();
  cy.get('#\\:r39\\:').click();
  cy.get('[data-testid="ArrowForwardIosIcon"]').click();
  cy.get('#\\:r63\\:').click();
  cy.get('#\\:r65\\:').clear('S');
  cy.get('#\\:r65\\:').type('Skill 1');
  cy.get('#\\:r67\\:').click();
  cy.get('#\\:r65\\:').clear('S');
  cy.get('#\\:r65\\:').type('Skill 2');
  cy.get('#\\:r67\\:').click();
  cy.get('#\\:r69\\:').clear('L');
  cy.get('#\\:r69\\:').type('Language 1');
  cy.get('.MuiSlider-root').click();
  cy.get('#\\:r6b\\:').click();
  cy.get('.css-149sczi > .MuiFormControl-root').click();
  cy.get('#\\:r69\\:').clear();
  cy.get('#\\:r69\\:').type('Language 2');
  cy.get('.MuiSlider-root').click();
  cy.get('#\\:r6b\\:').click();
  cy.get(':nth-child(6) > .MuiAccordion-heading > #panel1-header > .MuiAccordionSummary-content').click();
  cy.get('.css-11v9m8c > .MuiPaper-root > .MuiAccordion-heading > #panel1-header > .MuiAccordionSummary-content').click();
  cy.get('[data-testid="ArrowForwardIosIcon"]').click();
  cy.get('.MuiToggleButtonGroup-lastButton').click();
  cy.get(':nth-child(1) > .MuiBox-root > input').click();
  cy.get('.css-1uqux2c').click();
  cy.get(':nth-child(2) > .MuiBox-root > input').click();
  cy.get('.page-header').click();
  cy.get(':nth-child(3) > .MuiBox-root > input').click();
  cy.get('.css-1uqux2c').click();
  cy.get('.right-align > span').click();
  /* ==== End Cypress Studio ==== */
});